export type ScreenType = 
  | 'SPLASH' 
  | 'ONBOARDING' 
  | 'AUTH' 
  | 'PROFILE_SETUP' 
  | 'MAP'
  | 'HOME' 
  | 'VENUE_DETAIL' 
  | 'CHAT' 
  | 'QR_SCANNER' 
  | 'SETTINGS' 
  | 'CHAT_LIST'
  | 'EDIT_PROFILE'
  | 'SAVED_VENUES'
  | 'NOTIFICATIONS'
  | 'ADMIN'
  | 'ACTIVE_USERS';
